list_1 = set(["White", "Black", "Red"])
list_2 = set(["Red", "Green"])
print("Original set elements:")
print(list_1)
print(list_2)
print("\nDifferenct of list_1 and list_2:")
print(list_1.difference(list_2))
print("\nDifferenct of list_2 and list_1:")
print(list_2.difference(list_1))
